"""
example_quokka_sharp.py
=======================
A hands-on playground for Quokka-Sharp.

Edit the four sections below (SIMULATE / VERIFY / EQUIVALENCE / SYNTHESIS),
then run:

    python example_quokka_sharp.py

Each section is independent — comment out the ones you don't need.

Prerequisites
-------------
    pip install quokka_sharp
    export QUOKKA_CONFIG=/path/to/config.json

QASM files used here live in ./qasm_fixtures/ (generated by the test suite).
You can also point any variable at your own .qasm file.
"""

import os
import decimal
import quokka_sharp as qk

# ─── helpers ──────────────────────────────────────────────────────────────────

def to_float(v) -> float:
    """Convert Decimal / float / int to plain Python float."""
    return float(v)

FIXTURES = os.path.join(os.path.dirname(__file__), "qasm_fixtures")

def fixture(subdir: str, filename: str) -> str:
    """Return the path to a bundled fixture file."""
    return os.path.join(FIXTURES, subdir, filename)

def section(title: str):
    width = 60
    print()
    print("═" * width)
    print(f"  {title}")
    print("═" * width)

def result_line(label: str, value):
    print(f"  {label:<30} {value}")

# ══════════════════════════════════════════════════════════════════════════════
# 1.  SIMULATION
#     Compute the probability of a measurement outcome after running a circuit.
# ══════════════════════════════════════════════════════════════════════════════

section("1 · SIMULATION")

# ── What to simulate ──────────────────────────────────────────────────────────
#
# qasmfile   : path to a .qasm circuit file
# basis      : "comp"  – computational basis  (recommended for most circuits)
#              "pauli" – Pauli basis
# measurement: "allzero"   – probability that ALL qubits read 0
#              "firstzero" – probability that the first qubit reads 0
#              {qubit_index: 0_or_1, ...} – specific outcome, e.g. {0:1, 1:0}
#
# Try changing any of the three variables below:

SIM_FILE        = fixture("multi_qubit", "bell.qasm")   # ← change me
SIM_BASIS       = "comp"                                 # ← "comp" or "pauli"
SIM_MEASUREMENT = "allzero"                              # ← "allzero" / "firstzero" / {0:1, 1:0} / ...

# ── Run ───────────────────────────────────────────────────────────────────────

prob = qk.functionalities.sim(
    qasmfile    = SIM_FILE,
    basis       = SIM_BASIS,
    measurement = SIM_MEASUREMENT,
)

result_line("Circuit:",      os.path.basename(SIM_FILE))
result_line("Basis:",        SIM_BASIS)
result_line("Measurement:",  SIM_MEASUREMENT)
result_line("Probability:",  prob if prob in ("TIMEOUT", "MEMOUT") else f"{to_float(prob):.10f}")

# ── More examples to try (uncomment one at a time) ────────────────────────────
#
# Single H gate → superposition, P(0) = 0.5
# SIM_FILE = fixture("single_qubit", "h.qasm"); SIM_MEASUREMENT = "allzero"
#
# X gate → bit-flip, P(0) = 0.0
# SIM_FILE = fixture("single_qubit", "x.qasm"); SIM_MEASUREMENT = "allzero"
#
# HH = identity, P(0) = 1.0
# SIM_FILE = fixture("single_qubit", "hh.qasm"); SIM_MEASUREMENT = "allzero"
#
# GHZ state: P(111) = 0.5
# SIM_FILE = fixture("multi_qubit", "ghz_3q.qasm"); SIM_MEASUREMENT = {0:1, 1:1, 2:1}
#
# 2-qubit QFT: all four outcomes equally likely (P = 0.25 each)
# SIM_FILE = fixture("multi_qubit", "qft_2q.qasm"); SIM_MEASUREMENT = {0:0, 1:1}
#
# Your own circuit:
# SIM_FILE = "/path/to/my_circuit.qasm"; SIM_MEASUREMENT = {0:0}


# ══════════════════════════════════════════════════════════════════════════════
# 2.  VERIFICATION
#     Check that a circuit maps a given input state to a given output state.
# ══════════════════════════════════════════════════════════════════════════════

section("2 · VERIFICATION")

# ── What to verify ────────────────────────────────────────────────────────────
#
# qasmfile : path to the circuit to verify
# basis    : "comp" or "pauli"
# precons  : dict of {qubit_index: value} — the required INPUT state
# postcons : dict of {qubit_index: value} — the required OUTPUT state
#
# Result: "True"  → the circuit always maps precons → postcons
#         "False" → it does NOT
#
# Try changing the variables below:

VER_FILE     = fixture("verify", "v04_cx_control1.qasm")  # ← change me
VER_BASIS    = "comp"                                      # ← "comp" or "pauli"
VER_PRECONS  = {0: 0, 1: 0}                               # ← input  state constraints
VER_POSTCONS = {0: 1, 1: 1}                               # ← output state constraints

# ── Run ───────────────────────────────────────────────────────────────────────

verified = qk.functionalities.verify(
    VER_FILE,
    basis    = VER_BASIS,
    precons  = VER_PRECONS,
    postcons = VER_POSTCONS,
)

result_line("Circuit:",      os.path.basename(VER_FILE))
result_line("Basis:",        VER_BASIS)
result_line("Precondition:", VER_PRECONS)
result_line("Postcondition:",VER_POSTCONS)
result_line("Result:",       verified)

# ── More examples to try (uncomment one at a time) ────────────────────────────
#
# X gate flips the qubit → True
# VER_FILE = fixture("verify", "v01_x_flip.qasm")
# VER_PRECONS = {0: 0}; VER_POSTCONS = {0: 1}
#
# X gate, wrong postcondition → False
# VER_FILE = fixture("verify", "v01_x_flip.qasm")
# VER_PRECONS = {0: 0}; VER_POSTCONS = {0: 0}
#
# Toffoli with both controls set → target flips
# VER_FILE = fixture("verify", "v06_toffoli_flip.qasm")
# VER_PRECONS = {0: 0, 1: 0, 2: 0}; VER_POSTCONS = {0: 1, 1: 1, 2: 1}
#
# Multi-gate chain X H H X = Identity → True
# VER_FILE = fixture("verify", "v10_multi_gate_chain.qasm")
# VER_PRECONS = {0: 0}; VER_POSTCONS = {0: 0}


# ══════════════════════════════════════════════════════════════════════════════
# 3.  EQUIVALENCE CHECKING
#     Decide whether two circuits implement the same unitary.
# ══════════════════════════════════════════════════════════════════════════════

section("3 · EQUIVALENCE CHECKING")

# ── Which circuits to compare ─────────────────────────────────────────────────
#
# qasmfile1, qasmfile2 : the two circuits to compare
# basis  : "comp" or "pauli"
# check  : "cyclic"        – recommended for computational basis
#           "linear"       – recommended for Pauli basis
#           "cyclic_linear" – combine both
# epsilon: tolerance (0 = exact equivalence)
#
# Result: True  → circuits are equivalent
#         False → they are NOT equivalent

EQ_FILE1   = fixture("equiv_pairs", "eq1_hh.qasm")       # ← change me
EQ_FILE2   = fixture("equiv_pairs", "eq1_identity.qasm")  # ← change me
EQ_BASIS   = "comp"                                        # ← "comp" or "pauli"
EQ_CHECK   = "cyclic"                                      # ← "cyclic" / "linear"
EQ_EPSILON = 0                                             # ← 0 for exact

# ── Run ───────────────────────────────────────────────────────────────────────

equiv = qk.functionalities.eq(
    EQ_FILE1,
    EQ_FILE2,
    basis   = EQ_BASIS,
    check   = EQ_CHECK,
    epsilon = EQ_EPSILON,
)

result_line("Circuit A:",  os.path.basename(EQ_FILE1))
result_line("Circuit B:",  os.path.basename(EQ_FILE2))
result_line("Basis:",      EQ_BASIS)
result_line("Check mode:", EQ_CHECK)
result_line("Equivalent:", equiv)

# ── More examples to try (uncomment one at a time) ────────────────────────────
#
# SS = Z  →  True
# EQ_FILE1 = fixture("equiv_pairs", "eq2_ss.qasm")
# EQ_FILE2 = fixture("equiv_pairs", "eq2_z.qasm")
# EQ_BASIS = "pauli"; EQ_CHECK = "linear"
#
# HXH = Z  →  True
# EQ_FILE1 = fixture("equiv_pairs", "eq3_hxh.qasm")
# EQ_FILE2 = fixture("equiv_pairs", "eq3_z.qasm")
#
# 3-CNOT SWAP = built-in SWAP  →  True
# EQ_FILE1 = fixture("equiv_pairs", "eq5_3cx_swap.qasm")
# EQ_FILE2 = fixture("equiv_pairs", "eq5_swap.qasm")
#
# H vs X  →  False (different unitaries)
# EQ_FILE1 = fixture("equiv_pairs", "neq1_h.qasm")
# EQ_FILE2 = fixture("equiv_pairs", "neq1_x.qasm")
#
# H vs HS  →  False
# EQ_FILE1 = fixture("equiv_pairs", "neq2_h.qasm")
# EQ_FILE2 = fixture("equiv_pairs", "neq2_hs.qasm")
# EQ_BASIS = "pauli"; EQ_CHECK = "linear"
#
# Two of your own circuits:
# EQ_FILE1 = "/path/to/circuit_a.qasm"
# EQ_FILE2 = "/path/to/circuit_b.qasm"


# ══════════════════════════════════════════════════════════════════════════════
# 4.  SYNTHESIS
#     Find the shortest circuit that implements a given target unitary,
#     using only gates from a chosen gate set.
#
#     NOTE: synthesis requires a *maximum* WMC solver (e.g. d4max).
#           Make sure your config.json points at d4max and sets D4ToolInvocation.
# ══════════════════════════════════════════════════════════════════════════════

section("4 · SYNTHESIS")

# ── What to synthesise ────────────────────────────────────────────────────────
#
# qasmfile : target circuit (the unitary you want to re-implement)
# gate_set : allowed gates — choose from: "h", "cx", "s", "t", "cz", "csqrtx"
#            Use either "t" or "csqrtx" to synthesise CCX, but not both.
# epsilon  : fidelity tolerance (0 = exact, 0 < epsilon < 1 = approximate)
#
# Returns (outcome, weight, qasm_string, layers):
#   outcome     : "FOUND" | "TIMEOUT" | "CRASH" | "ERROR#"
#   weight      : achieved fidelity (1.0 when FOUND with epsilon=0)
#   qasm_string : the synthesised circuit in QASM format
#   layers      : circuit depth of the best solution found

SYN_FILE     = fixture("synthesis", "syn01_h_target.qasm")  # ← change me
SYN_GATE_SET = {"h", "cx", "s"}                             # ← change me
SYN_EPSILON  = 0                                             # ← 0 for exact

# ── Run ───────────────────────────────────────────────────────────────────────

outcome, weight, qasm_str, layers = qk.functionalities.syn(
    SYN_FILE,
    epsilon  = SYN_EPSILON,
    gate_set = SYN_GATE_SET,
)

result_line("Target circuit:",  os.path.basename(SYN_FILE))
result_line("Gate set:",        str(SYN_GATE_SET))
result_line("Epsilon:",         SYN_EPSILON)
result_line("Outcome:",         outcome)
result_line("Fidelity (weight):",f"{float(weight):.6f}" if weight is not None else "—")
result_line("Depth (layers):",  layers)

if outcome == "FOUND" and qasm_str:
    print()
    print("  Synthesised circuit:")
    print("  " + "-" * 50)
    for line in qasm_str.strip().splitlines():
        print(f"    {line}")
    print("  " + "-" * 50)

# ── More examples to try (uncomment one at a time) ────────────────────────────
#
# Synthesise X using {h, cx, s}
# SYN_FILE = fixture("synthesis", "syn02_x_target.qasm")
# SYN_GATE_SET = {"h", "cx", "s"}
#
# Synthesise Z using {h, cx, s}  — should find S S
# SYN_FILE = fixture("synthesis", "syn03_z_target.qasm")
# SYN_GATE_SET = {"h", "cx", "s"}
#
# Synthesise T using {h, cx, t}
# SYN_FILE = fixture("synthesis", "syn05_t_target.qasm")
# SYN_GATE_SET = {"h", "cx", "t"}
#
# Synthesise Bell prep using {h, cx, s}
# SYN_FILE = fixture("synthesis", "syn07_bell_target.qasm")
# SYN_GATE_SET = {"h", "cx", "s"}
#
# Approximate synthesis (epsilon > 0): allow small fidelity loss
# SYN_EPSILON = 0.01

print()
