from comput2cnf_py_codegen import *

def add_sign(func, prefix = "", comment=""):
    print(prefix+f"        # adding sign if {func}")
    print(prefix+"        R = cnf.add_var()")
    print(prefix+"        cnf.vars.RVar.append(R)")    
    print(prefix+"        r = cnf.vars.r")
    print(prefix+"        cnf.vars.r = R")
    to_py(	                  Equivalent(R, r ^ func), prefix, comment="- "+comment)

def add_i(func, prefix = "", comment=""):
    print(prefix+f"        # adding i if {func}")
    print(prefix+"        I = cnf.add_var()")
    print(prefix+"        cnf.vars.IVar.append(I)")    
    print(prefix+"        i = cnf.vars.i")
    to_py(	                  Equivalent(I, i ^ func), prefix, comment="i "+comment)
    add_sign(i & ~I, prefix)
    print(prefix+"        cnf.vars.i = I")

def add_sqrt_half(func, prefix = "", comment=""):
    print(prefix+"        U = cnf.add_var()")
    print(prefix+"        cnf.vars.UVar.append(U)")    
    print(prefix+"        cnf.power_two_normalisation += 0.5 ")
    print(prefix+"        u = cnf.vars.u")
    print(prefix+"        cnf.vars.u = U")
    to_py(	                  Equivalent(U, u ^ ~func), prefix, comment="sqrt U update "+comment)
    print()
    print(prefix+"        D = cnf.add_var()")
    print(prefix+"        cnf.vars.DVar.append(D)")    
    print(prefix+f"        cnf.add_clause([D, cnf.add_var()], comment=\"sqrt D double {comment}\")")
    to_py(	                  Equivalent(D, u & ~U), prefix, comment="sqrt D update "+comment)

def main():

    print("# This code was generated by comput2cnf_py_codegen.py.")
    print("from decimal import Decimal")
    print("import math")
    print("from decimal import Decimal, getcontext")
    print("getcontext().prec = 32")
    print("from .pauli2cnf import pauli2cnf")
    print()
    print("class comput2cnf:")
    print('''    \"\"\"
    This class contains the functions to convert a quantum circuit to CNF clauses in the Computationl basis.
    \"\"\"''')
    print()

    # Initialization:
    print("    def init(cnf):")
    print("        cnf.i = cnf.add_var()")
    print("        cnf.add_clause([-cnf.i])")
    print("        cnf.r = cnf.add_var()")
    print("        cnf.add_clause([-cnf.r])")
    print("        cnf.u = cnf.add_var()")
    print("        cnf.add_clause([-cnf.u])")
    print()

    # H:
    print("    def H2CNF(cnf, k):")
    print("        x = cnf.vars.x")
    print()   
    print("        X = cnf.add_var()")
    print("        cnf.vars.XVar.append(X)")
    print()
    add_sqrt_half(true)
    print()
    add_sign(x[k] & X)
    print()
    print("        cnf.vars.x[k] = X")
    print()

    #CNOT
    print("    def CNOT2CNF(cnf, c, t):")
    print("        x = cnf.vars.x")
    print()
    print("        Xt = cnf.add_var()")
    print("        cnf.vars.XVar.append(Xt)")
    to_py(	       Equivalent(Xt, (x[c] ^ x[t])))
    print()
    print("        cnf.vars.x[t] = Xt")
    print()

    #TOFFOLI
    print("    def CCX2CNF(cnf, k, c, t):")
    print("        x = cnf.vars.x")
    print()
    print("        Xt = cnf.add_var()")
    print("        cnf.vars.XVar.append(Xt)")
    to_py(	       Equivalent(Xt, ((x[k] & x[c]) ^ x[t])))
    print()
    print("        cnf.vars.x[t] = Xt")
    print()

    #Z
    print("    def Z2CNF(cnf, k):")
    print("        x = cnf.vars.x")
    print()
    add_sign(x[k])
    print()

    #RZ(theta)
    print("    def RZ2CNF(cnf, k, theta):")
    print("        x = cnf.vars.x")
    print()
    print("        w = cnf.add_var()")
    print("        cnf.vars.UVar.append(w)")
    print("        cnf.add_weight(w, complex(Decimal(math.cos(theta)), Decimal(math.sin(theta))), 1)")
    to_py(	       Equivalent(w, x[k]), comment="w (RZ)")
    print()

    #S
    print("    def S2CNF(cnf, k):")
    print("        x = cnf.vars.x")
    print()
    add_i(x[k], comment="(S)")
    print()

    #Sdg
    print("    def Sdg2CNF(cnf, k):")
    print("        x = cnf.vars.x") 
    add_i(x[k], comment="(Sdg)")
    print()
    add_sign(x[k], comment="(Sdg)")
    print()

    #T
    print("    def T2CNF(cnf, k):")
    print("        x = cnf.vars.x")
    print("        i = cnf.vars.i")
    print()
    print("        I = cnf.add_var()")
    print("        cnf.vars.IVar.append(I)")
    to_py(             x[k] | Equivalent(I, i), comment="I (T)")
    print()
    add_sign(i & ~I, comment="(T)")
    print()
    add_sqrt_half(x[k], comment="(T)")
    print()
    print("        cnf.vars.i = I")

    #Tdg
    print("    def Tdg2CNF(cnf, k):")
    print("        x = cnf.vars.x")
    print("        i = cnf.vars.i")
    print()
    print("        I = cnf.add_var()")
    print("        cnf.vars.IVar.append(I)")
    to_py(             x[k] | Equivalent(I, i), comment="I (Tdg)")
    print()
    add_sign(~i & I, comment="(Tdg)")
    print()
    add_sqrt_half(x[k], comment="(Tdg)")
    print()
    print("        cnf.vars.i = I")

    #X
    print("    def X2CNF(cnf, k):")
    print("        x = cnf.vars.x")
    print()
    print("        X = cnf.add_var()")
    print("        cnf.vars.XVar.append(X)")
    to_py(         Equivalent(X, ~x[k]))
    print()
    print("        cnf.vars.x[k] = X")
    print()

    #Y
    print("    def Y2CNF(cnf, k):")
    print("        x = cnf.vars.x")
    print()
    print("        X = cnf.add_var()")
    print("        cnf.vars.XVar.append(X)")
    to_py(         Equivalent(X, ~x[k]), comment="Y gate")
    print()
    add_sign(x[k])
    print()
    add_i(true)
    print()
    print("        cnf.vars.x[k] = X")
    print()

    #RX(theta)
    print("    def RX2CNF(cnf, k, theta):")
    print("        x = cnf.vars.x")
    print("        X = cnf.add_var()")
    print("        cnf.vars.XVar.append(X)")
    print()
    print("        w = cnf.add_var()")
    print("        cnf.vars.UVar.append(w)")
    to_py(         Equivalent(w, Equivalent(x[k], X) ))
    print()
    print("        cnf.vars.x[k] = X")
    print()
    print("        cnf.add_weight(w, complex(Decimal(math.cos(theta/2)), Decimal(math.sin(theta/2))), complex(0, -Decimal(math.sin(theta/2))))")
    print()

    #CZ
    print("    def CZ2CNF(cnf, c, t):")
    print("        x = cnf.vars.x")
    print()
    print("        Xc = cnf.add_var()")
    print("        cnf.vars.XVar.append(Xc)")
    to_py(         Equivalent(Xc, x[c]))
    print()
    print("        Xt = cnf.add_var()")
    print("        cnf.vars.XVar.append(Xt)")
    to_py(         Equivalent(Xt, x[t]))
    print()
    print("        cnf.vars.x[c] = Xc")
    print("        cnf.vars.x[t] = Xt")
    print()
    add_sign(x[c] & x[t])
    print()

    #SWAP
    print("    def SWAP2CNF(cnf, c, t):")
    print("        x = cnf.vars.x")
    print()
    print("        x[c], x[t] = x[t], x[c]")
    print()


    # Synthesis
    add_synthesis()

if __name__ == "__main__":
    main()
