# This code was generated by comput2cnf_weighted_py_codegen.py.
from decimal import Decimal
import math
from decimal import Decimal, getcontext
getcontext().prec = 32
from .pauli2cnf import pauli2cnf

frac1sqrt2 = (Decimal(1) / Decimal(2)).sqrt()

class comput2cnf:
    """
    This class contains the functions to convert a quantum circuit to CNF clauses in the Computationl basis.
    """

    def init(cnf):
        return

    def H2CNF(cnf, k):
        x = cnf.vars.x

        X = cnf.add_var()
        cnf.vars.XVar.append(X)
        cnf.add_weight(x[k], frac1sqrt2, frac1sqrt2)

        # adding sign if X & x[k]
        R = cnf.add_var()
        cnf.vars.RVar.append(R)
        cnf.add_weight(R, -1, 1)
        # Equivalent(R, X & x[k])
        cnf.add_clause([-R,  X], comment="- ")
        cnf.add_clause([-R,  x[k]], comment="- ")
        cnf.add_clause([ R, -X, -x[k]], comment="- ")

        cnf.vars.x[k] = X

    def CNOT2CNF(cnf, c, t):
        x = cnf.vars.x

        Xt = cnf.add_var()
        cnf.vars.XVar.append(Xt)
        # Equivalent(Xt, x[c] ^ x[t])
        cnf.add_clause([ Xt,  x[c], -x[t]])
        cnf.add_clause([ Xt, -x[c],  x[t]])
        cnf.add_clause([-Xt,  x[c],  x[t]])
        cnf.add_clause([-Xt, -x[c], -x[t]])

        cnf.vars.x[t] = Xt

    def CCX2CNF(cnf, k, c, t):
        x = cnf.vars.x

        Xt = cnf.add_var()
        cnf.vars.XVar.append(Xt)
        # Equivalent(Xt, x[t] ^ (x[c] & x[k]))
        cnf.add_clause([ Xt,  x[c], -x[t]])
        cnf.add_clause([ Xt,  x[k], -x[t]])
        cnf.add_clause([-Xt,  x[c],  x[t]])
        cnf.add_clause([-Xt,  x[k],  x[t]])
        cnf.add_clause([ Xt, -x[c], -x[k],  x[t]])
        cnf.add_clause([-Xt, -x[c], -x[k], -x[t]])

        cnf.vars.x[t] = Xt

    def Z2CNF(cnf, k):
        x = cnf.vars.x
        cnf.add_weight(x[k], -1, 1)

    def RZ2CNF(cnf, k, theta):
        x = cnf.vars.x
        cnf.add_weight(x[k], complex(Decimal(math.cos(theta)), Decimal(math.sin(theta))), 1)

    def S2CNF(cnf, k):
        x = cnf.vars.x
        cnf.add_weight(x[k], 1j, 1)

    def Sdg2CNF(cnf, k):
        x = cnf.vars.x
        cnf.add_weight(x[k], -1j, 1)

    def T2CNF(cnf, k):
        x = cnf.vars.x
        cnf.add_weight(x[k], complex(frac1sqrt2,frac1sqrt2), 1)

    def Tdg2CNF(cnf, k):
        x = cnf.vars.x
        cnf.add_weight(x[k], complex(frac1sqrt2,-frac1sqrt2), 1)

    def X2CNF(cnf, k):
        x = cnf.vars.x

        X = cnf.add_var()
        cnf.vars.XVar.append(X)
        # Equivalent(X, ~x[k])
        cnf.add_clause([ X,  x[k]])
        cnf.add_clause([-X, -x[k]])

        cnf.vars.x[k] = X

    def Y2CNF(cnf, k):
        x = cnf.vars.x

        X = cnf.add_var()
        cnf.vars.XVar.append(X)
        # Equivalent(X, ~x[k])
        cnf.add_clause([ X,  x[k]], comment="Y gate")
        cnf.add_clause([-X, -x[k]], comment="Y gate")
        cnf.add_weight(x[k], -1j, 1j)

        cnf.vars.x[k] = X

    def RX2CNF(cnf, k, theta):
        x = cnf.vars.x
        X = cnf.add_var()
        cnf.vars.XVar.append(X)

        w = cnf.add_var()
        cnf.vars.UVar.append(w)
        # Equivalent(w, Equivalent(X, x[k]))
        cnf.add_clause([ X,  w,  x[k]])
        cnf.add_clause([ X, -w, -x[k]])
        cnf.add_clause([-X,  w, -x[k]])
        cnf.add_clause([-X, -w,  x[k]])
        cnf.add_weight(w, complex(Decimal(math.cos(theta/2)), 0), complex(0, -Decimal(math.sin(theta/2))))

        cnf.vars.x[k] = X

    def CZ2CNF(cnf, c, t):
        x = cnf.vars.x

        # adding sign if x[c] & x[t]
        R = cnf.add_var()
        cnf.vars.RVar.append(R)
        cnf.add_weight(R, -1, 1)
        # Equivalent(R, x[c] & x[t])
        cnf.add_clause([-R,  x[c]], comment="- ")
        cnf.add_clause([-R,  x[t]], comment="- ")
        cnf.add_clause([ R, -x[c], -x[t]], comment="- ")

    def SWAP2CNF(cnf, c, t):
        x = cnf.vars.x

        x[c], x[t] = x[t], x[c]




    def SynLayer2CNF(cnf):
        n = cnf.n
        x = cnf.vars.x
        X = [cnf.add_var() for _ in range(n)]
        R = [cnf.add_var() for _ in range(n)]
        U = [cnf.add_var() for _ in range(n)]
        Wp = [cnf.add_var() for _ in range(n)]
        Wn = [cnf.add_var() for _ in range(n)]
        [cnf.add_weight(R[k], -1, 1) for k in range(n)]
        [cnf.add_weight(U[k], (Decimal(1) / Decimal(2)).sqrt(), 1) for k in range(n)]
        [cnf.add_weight(Wp[k], complex((Decimal(1) / Decimal(2)).sqrt(), (Decimal(1) / Decimal(2)).sqrt()), 1) for k in range(n)]
        [cnf.add_weight(Wn[k], complex((Decimal(1) / Decimal(2)).sqrt(), -(Decimal(1) / Decimal(2)).sqrt()), 1) for k in range(n)]
        
        idg = [cnf.add_var(syn_gate_pick = True, Name = 'id', bits = [k]) for k in range(n)]
        hg = [cnf.add_var(syn_gate_pick = True, Name = 'h', bits = [k]) for k in range(n)]
        tg = [cnf.add_var(syn_gate_pick = True, Name = 't', bits = [k]) for k in range(n)]
        tdg = [cnf.add_var(syn_gate_pick = True, Name = 'tdg', bits = [k]) for k in range(n)]
        cg = [[cnf.add_var(syn_gate_pick = True, Name = 'cx', bits = [c,t]) if c!=t else None for t in range(n)] for c in range(n)]
        for k in range(n):
    
            # Implies(idg[k], Equivalent(X[k], x[k]))
            cnf.add_clause([ X[k], -idg[k], -x[k]])
            cnf.add_clause([-X[k], -idg[k],  x[k]])
            # Implies(idg[k], ~R[k])
            cnf.add_clause([-R[k], -idg[k]])
            # Implies(idg[k], ~U[k])
            cnf.add_clause([-U[k], -idg[k]])
            # Implies(idg[k], ~Wn[k] & ~Wp[k])
            cnf.add_clause([-Wn[k], -idg[k]])
            cnf.add_clause([-Wp[k], -idg[k]])
            # Implies(hg[k], Equivalent(R[k], X[k] & x[k]))
            cnf.add_clause([-R[k],  X[k], -hg[k]])
            cnf.add_clause([-R[k], -hg[k],  x[k]])
            cnf.add_clause([ R[k], -X[k], -hg[k], -x[k]])
            # Implies(hg[k], U[k])
            cnf.add_clause([ U[k], -hg[k]])
            # Implies(hg[k], ~Wn[k] & ~Wp[k])
            cnf.add_clause([-Wn[k], -hg[k]])
            cnf.add_clause([-Wp[k], -hg[k]])
            # Implies(tdg[k] | tg[k], Equivalent(X[k], x[k]))
            cnf.add_clause([ X[k], -tdg[k], -x[k]])
            cnf.add_clause([ X[k], -tg[k], -x[k]])
            cnf.add_clause([-X[k], -tdg[k],  x[k]])
            cnf.add_clause([-X[k], -tg[k],  x[k]])
            # Implies(tdg[k] | tg[k], ~R[k])
            cnf.add_clause([-R[k], -tdg[k]])
            cnf.add_clause([-R[k], -tg[k]])
            # Implies(tdg[k] | tg[k], ~U[k])
            cnf.add_clause([-U[k], -tdg[k]])
            cnf.add_clause([-U[k], -tg[k]])
            # (Implies(tdg[k], ~Wp[k] & (Equivalent(Wn[k], x[k])))) & (Implies(tg[k], ~Wn[k] & (Equivalent(Wp[k], x[k]))))
            cnf.add_clause([-Wn[k], -tg[k]])
            cnf.add_clause([-Wp[k], -tdg[k]])
            cnf.add_clause([ Wn[k], -tdg[k], -x[k]])
            cnf.add_clause([ Wp[k], -tg[k], -x[k]])
            cnf.add_clause([-Wn[k], -tdg[k],  x[k]])
            cnf.add_clause([-Wp[k], -tg[k],  x[k]])

            c = k
            for t in range(n):
                if t==c:
                    continue
    
                # Implies(cg[c][t], Equivalent(X[c], x[c]))
                cnf.add_clause([ X[c], -cg[c][t], -x[c]])
                cnf.add_clause([-X[c], -cg[c][t],  x[c]])
                # Implies(cg[c][t], Equivalent(X[t], x[c] ^ x[t]))
                cnf.add_clause([ X[t], -cg[c][t],  x[c], -x[t]])
                cnf.add_clause([ X[t], -cg[c][t], -x[c],  x[t]])
                cnf.add_clause([-X[t], -cg[c][t],  x[c],  x[t]])
                cnf.add_clause([-X[t], -cg[c][t], -x[c], -x[t]])
                # Implies(cg[c][t], ~R[c])
                cnf.add_clause([-R[c], -cg[c][t]])
                # Implies(cg[c][t], ~R[t])
                cnf.add_clause([-R[t], -cg[c][t]])
                # Implies(cg[c][t], ~U[c])
                cnf.add_clause([-U[c], -cg[c][t]])
                # Implies(cg[c][t], ~U[t])
                cnf.add_clause([-U[t], -cg[c][t]])
                # Implies(cg[c][t], ~Wn[c] & ~Wp[c])
                cnf.add_clause([-Wn[c], -cg[c][t]])
                cnf.add_clause([-Wp[c], -cg[c][t]])
                # Implies(cg[c][t], ~Wn[t] & ~Wp[t])
                cnf.add_clause([-Wn[t], -cg[c][t]])
                cnf.add_clause([-Wp[t], -cg[c][t]])

          
            cgs_k = [cg[k][i] for i in range(n) if i!=k] + [cg[i][k] for i in range(n) if i!=k]
            gate_controlers = [idg[k], hg[k], tg[k], tdg[k]]+cgs_k
            pauli2cnf.AMO(cnf, gate_controlers)
          
            if cnf.syn_gate_layer>=2:
                # H -> !l_H
                cnf.add_clause([-hg[k],  -cnf.get_syn_var_past_layer(Name ='h', bit = k)])
                # T -> !l_Tdg
                cnf.add_clause([-tg[k],  -cnf.get_syn_var_past_layer(Name ='tdg', bit = k)])
                # Tdg -> !l_T
                cnf.add_clause([-tdg[k], -cnf.get_syn_var_past_layer(Name ='t', bit = k)])
                # I -> I until CX
                cnf.add_clause([-cnf.get_syn_var_past_layer(Name ='id', bit = k), idg[k]] + cgs_k)

            if cnf.syn_gate_layer>=5:
                # T -> !l_T | !ll_T | !lll_T | !llll_T
                cnf.add_clause([-tg[k]] + [-cnf.get_syn_var_past_layer(Name ='t', bit = k, past=p) for p in range(1, 5)])
                # Tdg -> !l_Tdg | !ll_Tdg | !lll_Tdg | !llll_Tdg
                cnf.add_clause([-tdg[k]] + [-cnf.get_syn_var_past_layer(Name ='tdg', bit = k, past=p) for p in range(1, 5)])

            c = k
            for t in range(n):
                if c!=t:
                    if cnf.syn_gate_layer>=2:
                        # CX(c,t) -> !past(CX(c,t))
                        cnf.add_clause([-cg[c][t], -cnf.get_syn_var_past_layer(Name ='cx', bit = [c,t])])
                        # CX(c,t) -> !past(I(c)) or !past(I(t))
                        cnf.add_clause([-cg[c][t], -cnf.get_syn_var_past_layer(Name ='id', bit = c), -cnf.get_syn_var_past_layer(Name ='id', bit = t)])
            
                    if cnf.syn_gate_layer>=3:
                        # past(CX(c,t)) -> !past(past(T(c))) or !Tdg(c))
                        cnf.add_clause([-cnf.get_syn_var_past_layer(Name ='cx', bit = [c,t]), -cnf.get_syn_var_past_layer(Name ='tdg', bit = c, past=2), -tg[c]])
                        # past(CX(c,t)) -> !past(past(Tdg(c))) or !T(c))
                        cnf.add_clause([-cnf.get_syn_var_past_layer(Name ='cx', bit = [c,t]), -cnf.get_syn_var_past_layer(Name ='t', bit = c, past=2), -tdg[c]])
        
        cnf.vars.x[:n] = X
    
    
    
