# This code was generated by cnf2py.py.

# Equivalent(R, r ^ (x[k] & z[k]))
def H2CNF(tab, cnf, k):
    r = tab.r
    x = tab.x
    z = tab.z
    R = cnf.add_var()
    cnf.add_clause([ R, -r,  x[k]])
    cnf.add_clause([ R, -r,  z[k]])
    cnf.add_clause([-R,  r,  x[k]])
    cnf.add_clause([-R,  r,  z[k]])
    cnf.add_clause([ R,  r, -x[k], -z[k]])
    cnf.add_clause([-R, -r, -x[k], -z[k]])
    x[k], z[k] = z[k], x[k]

    tab.r = R

# Equivalent(R, r ^ (x[k] & z[k]))
# Equivalent(Z, x[k] ^ z[k])
def S2CNF(tab, cnf, k):
    r = tab.r
    x = tab.x
    z = tab.z
    R = cnf.add_var()
    cnf.add_clause([ R, -r,  x[k]])
    cnf.add_clause([ R, -r,  z[k]])
    cnf.add_clause([-R,  r,  x[k]])
    cnf.add_clause([-R,  r,  z[k]])
    cnf.add_clause([ R,  r, -x[k], -z[k]])
    cnf.add_clause([-R, -r, -x[k], -z[k]])

    Z = cnf.add_var()
    cnf.add_clause([ Z,  x[k], -z[k]])
    cnf.add_clause([ Z, -x[k],  z[k]])
    cnf.add_clause([-Z,  x[k],  z[k]])
    cnf.add_clause([-Z, -x[k], -z[k]])

    tab.z[k] = Z
    tab.r = R

# Equivalent(R, r ^ z[k])
def X2CNF(tab, cnf, k):
    r = tab.r
    z = tab.z
    R = cnf.add_var()
    cnf.add_clause([ R,  r, -z[k]])
    cnf.add_clause([ R, -r,  z[k]])
    cnf.add_clause([-R,  r,  z[k]])
    cnf.add_clause([-R, -r, -z[k]])

    tab.r = R

# Equivalent(R, r ^ x[k] ^ z[k])
def Y2CNF(tab, cnf, k):
    r = tab.r
    x = tab.x
    z = tab.z
    R = cnf.add_var()
    cnf.add_clause([ R,  r,  x[k], -z[k]])
    cnf.add_clause([ R,  r, -x[k],  z[k]])
    cnf.add_clause([ R, -r,  x[k],  z[k]])
    cnf.add_clause([-R,  r,  x[k],  z[k]])
    cnf.add_clause([ R, -r, -x[k], -z[k]])
    cnf.add_clause([-R,  r, -x[k], -z[k]])
    cnf.add_clause([-R, -r,  x[k], -z[k]])
    cnf.add_clause([-R, -r, -x[k],  z[k]])

    tab.r = R

# Equivalent(R, r ^ x[k])
def Z2CNF(tab, cnf, k):
    r = tab.r
    x = tab.x
    R = cnf.add_var()
    cnf.add_clause([ R,  r, -x[k]])
    cnf.add_clause([ R, -r,  x[k]])
    cnf.add_clause([-R,  r,  x[k]])
    cnf.add_clause([-R, -r, -x[k]])

    tab.r = R

# Equivalent(R, r ^ (x[k] & ~z[k]))
# Equivalent(Z, x[k] ^ z[k])
def Sdg2CNF(tab, cnf, k):
    r = tab.r
    x = tab.x
    z = tab.z
    R = cnf.add_var()
    cnf.add_clause([ R, -r,  x[k]])
    cnf.add_clause([-R,  r,  x[k]])
    cnf.add_clause([ R, -r, -z[k]])
    cnf.add_clause([-R,  r, -z[k]])
    cnf.add_clause([ R,  r, -x[k],  z[k]])
    cnf.add_clause([-R, -r, -x[k],  z[k]])

    Z = cnf.add_var()
    cnf.add_clause([ Z,  x[k], -z[k]])
    cnf.add_clause([ Z, -x[k],  z[k]])
    cnf.add_clause([-Z,  x[k],  z[k]])
    cnf.add_clause([-Z, -x[k], -z[k]])

    tab.z[k] = Z
    tab.r = R

# Equivalent(R, r ^ (x[k] & z[k] & ~Z))
# x[k] | (Equivalent(Z, z[k]))
# Equivalent(u, x[k])
def T2CNF(tab, cnf, k):
    r = tab.r
    x = tab.x
    z = tab.z
    R = cnf.add_var()
    Z = cnf.add_var()
    cnf.add_clause([ R, -r,  x[k]])
    cnf.add_clause([ R, -r,  z[k]])
    cnf.add_clause([-R,  r,  x[k]])
    cnf.add_clause([-R,  r,  z[k]])
    cnf.add_clause([ R, -Z, -r])
    cnf.add_clause([-R, -Z,  r])
    cnf.add_clause([ R,  Z,  r, -x[k], -z[k]])
    cnf.add_clause([-R,  Z, -r, -x[k], -z[k]])

    cnf.add_clause([ Z,  x[k], -z[k]])
    cnf.add_clause([-Z,  x[k],  z[k]])

    u = cnf.add_var()
    cnf.add_clause([ u, -x[k]])
    cnf.add_clause([-u,  x[k]])
    cnf.add_weight(u, 0.707106781186548)

    tab.z[k] = Z
    tab.r = R

# Equivalent(R, r ^ (Z & x[k] & ~z[k]))
# x[k] | (Equivalent(Z, z[k]))
# Equivalent(u, x[k])
def Tdg2CNF(tab, cnf, k):
    r = tab.r
    x = tab.x
    z = tab.z
    R = cnf.add_var()
    Z = cnf.add_var()
    cnf.add_clause([ R,  Z, -r])
    cnf.add_clause([ R, -r,  x[k]])
    cnf.add_clause([-R,  Z,  r])
    cnf.add_clause([-R,  r,  x[k]])
    cnf.add_clause([ R, -r, -z[k]])
    cnf.add_clause([-R,  r, -z[k]])
    cnf.add_clause([ R, -Z,  r, -x[k],  z[k]])
    cnf.add_clause([-R, -Z, -r, -x[k],  z[k]])

    cnf.add_clause([ Z,  x[k], -z[k]])
    cnf.add_clause([-Z,  x[k],  z[k]])

    u = cnf.add_var()
    cnf.add_clause([ u, -x[k]])
    cnf.add_clause([-u,  x[k]])
    cnf.add_weight(u, 0.707106781186548)

    tab.z[k] = Z
    tab.r = R

# Equivalent(R, r ^ (x[c] & z[t] & (z[c] ^ ~x[t])))
# Equivalent(X, x[c] ^ x[t])
# Equivalent(Z, z[c] ^ z[t])
def CNOT2CNF(tab, cnf, c, t):
    r = tab.r
    x = tab.x
    z = tab.z
    R = cnf.add_var()
    Z = cnf.add_var()
    X = cnf.add_var()
    cnf.add_clause([ R, -r,  x[c]])
    cnf.add_clause([ R, -r,  z[t]])
    cnf.add_clause([-R,  r,  x[c]])
    cnf.add_clause([-R,  r,  z[t]])
    cnf.add_clause([ R, -r,  x[t], -z[c]])
    cnf.add_clause([ R, -r, -x[t],  z[c]])
    cnf.add_clause([-R,  r,  x[t], -z[c]])
    cnf.add_clause([-R,  r, -x[t],  z[c]])
    cnf.add_clause([ R,  r, -x[c],  x[t],  z[c], -z[t]])
    cnf.add_clause([ R,  r, -x[c], -x[t], -z[c], -z[t]])
    cnf.add_clause([-R, -r, -x[c],  x[t],  z[c], -z[t]])
    cnf.add_clause([-R, -r, -x[c], -x[t], -z[c], -z[t]])

    cnf.add_clause([ X,  x[c], -x[t]])
    cnf.add_clause([ X, -x[c],  x[t]])
    cnf.add_clause([-X,  x[c],  x[t]])
    cnf.add_clause([-X, -x[c], -x[t]])

    cnf.add_clause([ Z,  z[c], -z[t]])
    cnf.add_clause([ Z, -z[c],  z[t]])
    cnf.add_clause([-Z,  z[c],  z[t]])
    cnf.add_clause([-Z, -z[c], -z[t]])
    tab.x[t] = X
    tab.z[c] = Z
    tab.r = R

# Equivalent(R, r ^ (x[c] & z[t] & (x[t] ^ ~z[c])) ^ ((x[c] ^ x[t]) & (z[c] ^ z[t]) & (x[t] ^ ~z[c])))
# Equivalent(X, x[c] ^ x[t])
# Equivalent(Z, z[c] ^ z[t])
def CZ2CNF(tab, cnf, c, t):
    r = tab.r
    x = tab.x
    z = tab.z
    R = cnf.add_var()
    Z = cnf.add_var()
    X = cnf.add_var()
    cnf.add_clause([ R, -r,  x[t]])
    cnf.add_clause([ R, -r,  z[c]])
    cnf.add_clause([-R,  r,  x[t]])
    cnf.add_clause([-R,  r,  z[c]])
    cnf.add_clause([ R, -r,  x[c], -z[t]])
    cnf.add_clause([ R, -r, -x[c],  z[t]])
    cnf.add_clause([-R,  r,  x[c], -z[t]])
    cnf.add_clause([-R,  r, -x[c],  z[t]])
    cnf.add_clause([ R,  r,  x[c], -x[t], -z[c],  z[t]])
    cnf.add_clause([ R,  r, -x[c], -x[t], -z[c], -z[t]])
    cnf.add_clause([-R, -r,  x[c], -x[t], -z[c],  z[t]])
    cnf.add_clause([-R, -r, -x[c], -x[t], -z[c], -z[t]])

    cnf.add_clause([ X,  x[c], -x[t]])
    cnf.add_clause([ X, -x[c],  x[t]])
    cnf.add_clause([-X,  x[c],  x[t]])
    cnf.add_clause([-X, -x[c], -x[t]])

    cnf.add_clause([ Z,  z[c], -z[t]])
    cnf.add_clause([ Z, -z[c],  z[t]])
    cnf.add_clause([-Z,  z[c],  z[t]])
    cnf.add_clause([-Z, -z[c], -z[t]])
    tab.x[c] = tab.x[t]
    tab.x[t] = X
    tab.z[t] = tab.z[c]
    tab.z[c] = Z
    tab.r = R

# Equivalent(R, r ^ (x[k] & z[k] & ~Z))
# x[k] | (Equivalent(Z, z[k]))
# Equivalent(u, x[k])
def RZ2CNF(tab, cnf, k, cos_theta, sin_theta):
    r = tab.r
    x = tab.x
    z = tab.z
    R = cnf.add_var()
    Z = cnf.add_var()
    cnf.add_clause([ R, -r,  x[k]])
    cnf.add_clause([ R, -r,  z[k]])
    cnf.add_clause([-R,  r,  x[k]])
    cnf.add_clause([-R,  r,  z[k]])
    cnf.add_clause([ R, -Z, -r])
    cnf.add_clause([-R, -Z,  r])
    cnf.add_clause([ R,  Z,  r, -x[k], -z[k]])
    cnf.add_clause([-R,  Z, -r, -x[k], -z[k]])

    cnf.add_clause([ Z,  x[k], -z[k]])
    cnf.add_clause([-Z,  x[k],  z[k]])

    u1 = cnf.add_var()
    cnf.add_clause([-u1,  x[k]])
    cnf.add_clause([ Z, -u1, -z[k]])
    cnf.add_clause([-Z, -u1,  z[k]])
    cnf.add_clause([ Z,  u1, -x[k],  z[k]])
    cnf.add_clause([-Z,  u1, -x[k], -z[k]])
    cnf.add_weight( u1, cos_theta)
    cnf.add_weight(-u1, 1)

    u2 = cnf.add_var()
    cnf.add_clause([-u2,  x[k]])
    cnf.add_clause([ Z, -u2,  z[k]])
    cnf.add_clause([-Z, -u2, -z[k]])
    cnf.add_clause([ Z,  u2, -x[k], -z[k]])
    cnf.add_clause([-Z,  u2, -x[k],  z[k]])
    cnf.add_weight( u2, sin_theta)
    cnf.add_weight(-u2, 1)
    tab.z[k] = Z
    tab.r = R

# Equivalent(R, r ^ (X & z[k] & ~x[k]))
# z[k] | (Equivalent(X, x[k]))
# Equivalent(u, x[k])
def RX2CNF(tab, cnf, k, cos_theta, sin_theta):
    r = tab.r
    x = tab.x
    z = tab.z
    R = cnf.add_var()
    X = cnf.add_var()
    cnf.add_clause([ R,  X, -r])
    cnf.add_clause([ R, -r,  z[k]])
    cnf.add_clause([-R,  X,  r])
    cnf.add_clause([-R,  r,  z[k]])
    cnf.add_clause([ R, -r, -x[k]])
    cnf.add_clause([-R,  r, -x[k]])
    cnf.add_clause([ R, -X,  r,  x[k], -z[k]])
    cnf.add_clause([-R, -X, -r,  x[k], -z[k]])

    cnf.add_clause([ X, -x[k],  z[k]])
    cnf.add_clause([-X,  x[k],  z[k]])

    u1 = cnf.add_var()
    cnf.add_clause([-u1,  z[k]])
    cnf.add_clause([ X, -u1, -x[k]])
    cnf.add_clause([-X, -u1,  x[k]])
    cnf.add_clause([ X,  u1,  x[k], -z[k]])
    cnf.add_clause([-X,  u1, -x[k], -z[k]])
    cnf.add_weight( u1, cos_theta)
    cnf.add_weight(-u1, 1)

    u2 = cnf.add_var()
    cnf.add_clause([-u2,  z[k]])
    cnf.add_clause([ X, -u2,  x[k]])
    cnf.add_clause([-X, -u2, -x[k]])
    cnf.add_clause([ X,  u2, -x[k], -z[k]])
    cnf.add_clause([-X,  u2,  x[k], -z[k]])
    cnf.add_weight( u2, sin_theta)
    cnf.add_weight(-u2, 1)
    tab.x[k] = X
    tab.r = R

